### ISSUE TITLE
Experiment nimble dependencies management

### ISSUE THREAD

**Issue by 2-towns** [codex-storage/nim-codex#1014]
After a discussion with @gmega, we decided to give a try to managing the dependencies with Nimble instead of using sub-modules.

The problem we currently have with sub-modules is the pain of updating because you have to go manually for each dependency, update the version, and the versions of the sub-dependencies.

Nimble would make our lives easier because it would fetch the dependencies automatically, and we could lock the versions into a `nimble.lock` file.

So the idea would be to fetch the dependencies with Nimble and keep building with the Nimbus build system.

We may need to create a symbolic link from the Nimble `pkgs2` folder to the `vendor` folder to make the Nimbus build system recognize the dependencies (similarly to what the Nimbus build system does in the `pkgs` folder).

**Comment by gmega** [comment]
To give context: you'll only need to do the symbolic linking as long as you want to run hybrid builds. If you could move all deps to nimble, then that'd no longer be needed.

**Comment by dryajov** [comment]
I'm not sure this is needed, we aren't moving away from the nimbus-build-system in codex any time soon, nimble should be only used for the third party dependencies that live under the `vendors` folder.

**Comment by gmega** [comment]
Yeah, the reason is that @2-towns asked me why we don't do lock files and nimble, and I explained it to him that it was quite painful to manage things this way, but that I haven't tried to do it in a while. So I gave him some overall directions on the why of nimbus-build-system, and some short leeway to experiment with nimble if he wanted (also for him to be convinced that it's not the right approach).

**Comment by 2-towns** [comment]
I am still not convinced :). Currently, in my attempt, Nimble is not perfect, but it is working (almost well) when trying to retrieve the sub-dependencies (which is the main reason to use it in our case). So the idea is not to move away from the nimbus-build-system, but to integrate Nimble and manage the dependencies only.

However, I am fine if you prefer to maintain the current management with the sub-modules.

I think I have updated half of the dependencies now. So which direction should I take? Should I continue with Nimble, or should I abandon this experiment and update the sub-modules?

**Comment by 2-towns** [comment]
Okay, so actually, [nimbus-build-system has a hard-coded version of nimble](https://github.com/status-im/nimbus-build-system/blob/8fafcd0bac9f409091b7bcaee62ab6330f57441e/scripts/build_nim.sh#L165), which is 0.13.1.

A [PR](https://github.com/status-im/nimbus-build-system/pull/71) was created to make the NIMBLE_COMMIT customizable, but it was closed yesterday.

So the summary I can make at this point is:

1. Nimble works great when retrieving sub-dependencies. You can have multiple versions of a sub-dependency without conflict because the resolution is based on the commit hash.

2. In our case, many dependencies don't have versions, so is it worth it?

3. The nimbus-build-system uses an old version of nimble (0.13.1) that does not support .lock files and uses the pkgs folder (which has since been moved to pkgs2). Therefore, we will need to maintain symbolic links between pkgs2 and pkgs.

**Comment by dryajov** [comment]
The nimbus build system doesn't rely on nimble, what we should do is bump the deps in the vendor directory manually and make sure things compile and run.

**Comment by arnetheduck** [comment]
> A https://github.com/status-im/nimbus-build-system/pull/71 was created to make the NIMBLE_COMMIT customizable,

That PR changed a bit more than is necessary, but the aim is to upgrade n-b-s to nimble 0.16.4 as soon as that is released. It's waiting for a fix in nimble so that it can be compiled with nim 1.6. PR:s welcome (the above closed PR contained other changes that are not relevant for the moment)
