### ISSUE TITLE
Stress test on testnet

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#140]
Meets expected testing metrics (to be defined)

Test a range of files sizes and quantity across a range of network conditions. Could use a testbed like [Testground](https://github.com/testground/testground).

Testnet access: https://github.com/status-im/infra-codex

**Comment by Bulat-Ziganshin** [comment]
I think we can consider #131 as part of this process

**Comment by emizzle** [comment]
Yes, good point, thanks.

**Comment by leobago** [comment]
The idea is to scale in number of instances, starting from 16 instances up to 128 instances.

For each of the four node instances (16, 32, 64, 128) we will perform 64 runs.

In each run we will create an increasing number of files, starting from 64 up to 8192. The size of the files will be determined randomly at the time of creation, varying between 4KB and 4GB.

The test is successful if:
 * A 100% of files were successfully uploaded/downloaded
 * A 100% of files have perfect data integrity (no corrupted data)
 * The upload/download speed is within the expected range according to the network bandwidth (TBD once we have the testing platform)

**Comment by leobago** [comment]
Great idea @Bulat-Ziganshin. Perhaps similar tests can be done for #131 at a lower scale (4-8 instances). In order to determine the _expected speed_ we can first measure the time of raw data read/transfer/write between instances and add some overhead to it (X%), then we will know what the allowed speed is for our tests with Codex.

**Comment by michaelsbradleyjr** [comment]
> Actually, I've asked myself how to configure #131 tests and now we got some template for that. Great! @michaelsbradleyjr, can you translate this scenario into code for blockstore benchmark testing?

Sorry, I missed your comment/question in relation to #131. Will do.

**Comment by emizzle** [comment]
Based on 28/7/2022 meeting, we need four versions of stress tests:
1. Simple test, perhaps as part of `make testall`.
2. Larger file test, possible part of the make, eg `make testlarge`. This would pass a parameter to the simple smaller test in the point above.
3. As part of CI, a small testground mesh network with small file tests.
4. A more complex testground mesh netwokr setup with complex tests (@cskiraly mentioned he wanted to explore this a bit further).
