### ISSUE TITLE
Enhance block store api to work with lists of blocks

### ISSUE THREAD

**Issue by dryajov** [codex-storage/nim-codex#158]
The current api operates on single blocks, it could be a good enhancement to add complementary calls that operate on lists of blocks, for example `getBlocks/delBlocks/putBlocks/etc...`.

**Comment by Bulat-Ziganshin** [comment]
getBlocks(array of cid): iterator
delBlocks(array of cid): void
putBlocks - probably doesn't make much sense

anyway, these APIs should be implemented only when we will have some actual use for them
