### ISSUE TITLE
Pay hosts for time interval that they fill a slot

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#233]

**Comment by emizzle** [comment]
I believe this may have been covered in https://github.com/status-im/dagger-contracts/pull/13/commits/96b6638e8e5c9643902d25e4fbe05f28f2e51408?

**Comment by emizzle** [comment]
From what I understand, the `payoutSlot` function (in `Marketplace.sol`) needs to be triggered once a contract has finished. Perhaps the interaction could be such that a host tracks the contract end time locally, and requests a payout. This transaction could set the contract state to finished (we could also have a calculated property) and it could also pay out all other hosts. The first host would have to pay the gas for the transaction to pay out all hosts. Thoughts?

**Comment by markspanbroek** [comment]
Currently `payoutSlot()` pays out a fee for the entire duration of the contract. It should only pay out the duration that a host actually filled the slot.

It's ok that hosts should call `payoutSlot()` themselves; in fact I prefer it that way. We'd complicate things if we try to payout hosts when the contract finishes.

**Comment by AuHau** [comment]
Closed here https://github.com/codex-storage/nim-codex/pull/561
