### ISSUE TITLE
Crash when filling slot

### ISSUE THREAD

**Issue by markspanbroek** [codex-storage/nim-codex#243]
As reported by @dryajov, test for filling a slot crashes randomly in CI:

https://github.com/status-im/nim-codex/runs/8254603121?check_suite_focus=true

**Comment by markspanbroek** [comment]
The CI log does not contain a lot of useful information because the actual exception that is thrown is not show. This has been fixed in asynctest 0.3.2, but wasn't updated yet in Codex. I pushed #244 to remedy this.

I'm unable to reproduce the test failure locally, so I suggest we merge #244 and then wait for the failure to happen again. We should then have a log of the exception that causes it.

**Comment by gmega** [comment]
I guess we can close this by now, @markspanbroek?

**Comment by markspanbroek** [comment]
> I guess we can close this by now, @markspanbroek?

Yes, thanks for reminding me!
