### ISSUE TITLE
[BUG] make update overwrite working tree code changes

### ISSUE THREAD

**Issue by cskiraly** [codex-storage/nim-codex#361]
**Describe the bug**
in some cases `make update` can overwrite changes in the git working tree

**To Reproduce**

1, modify submodule of submodule
```
nim-codex % git diff                                  
diff --git a/vendor/nimbus-build-system b/vendor/nimbus-build-system
--- a/vendor/nimbus-build-system
+++ b/vendor/nimbus-build-system
@@ -1 +1 @@
-Subproject commit 1cf6a1b18ca5aa0d24e7a2861dd85d79ad9cb0cd
+Subproject commit 1cf6a1b18ca5aa0d24e7a2861dd85d79ad9cb0cd-dirty
nim-codex % git submodule foreach --recursive git diff
[...]
Entering 'vendor/nimbus-build-system/vendor/Nim-csources-v1'
diff --git a/makefile b/makefile
index 503c030..9326ac3 100644
--- a/makefile
+++ b/makefile
@@ -3,7 +3,7 @@
 CC ?= gcc
-CFLAGS += -Ic_code -w -O3 -fno-strict-aliasing
+CFLAGS += -Ic_code -w -O3 -fno-strict-aliasing -v
 LDFLAGS +=
[...] 
```
2, run update
```
nim-codex % make update
 m vendor/nimbus-build-system
^---top level
 m vendor/Nim-csources-v1
^---vendor/nimbus-build-system
 M makefile
^---vendor/Nim-csources-v1
Creating nimbus-build-system.paths
```
3, wonder where your changes have gone
```
nim-codex % git diff   
```

**Expected behavior**
changes are not overwritten

**Environment:**
 - OS: MacOs 11.6.1
 - Tag/Commit: 7a0a48e
 - Arch: AARCH64

**Additional context**
This is just to document the issue. As discussed in another thread, this might be a wontfix as we might change to nimble build system.

**Comment by gmega** [comment]
This seems very low priority, as in general I think we should not expect the contents of `/vendor` to survive a `make update`.

**Comment by gmega** [comment]
Closing as per the above reasoning.
