### ISSUE TITLE
[marketplace] ensure random slot index is not already taken

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#371]
When storage is requested, and that event is handled on a host, we assign a random slot index and kick off the sales state machine process. We may need to perform a check to ensure that the random slot is not already taken by another host.

In addition, later in the state machine process after we've downloaded the data and generated a proof, we attempt to fill the slot by calling `fillSlot` with the proof and the slot index randomly assigned. Perhaps at that point, that particular slot index may already be filled (`fillSlot` would return a `"Slot is not free"` error), at which point we could attempt to reassign a random slot index (check that it's not already in use), and call `fillSlot` again. Repeat until all possible slots have been tried or the slot filling was successful.

**Comment by emizzle** [comment]
Good point! However, we are currently downloading the entire dataset as the request contains the manifest cid: https://github.com/status-im/nim-codex/blob/3eacdd8a30a8bc4747a84ebb9e2dbe339da40a4e/codex/node.nim#L338-L359.

I'm likely wrong, but I do also wonder how we know which slot is meant to download which cid, as the erasure coding parameters are meant to influence the number of slots (or vice versa, see https://discord.com/channels/895609329053474826/1025042999748591656/1085145620702048341). This is also very relevant in a repair situation, as it would be the same process of downloading specific cids (and not the entire dataset). @dryajov at one point mentioned this is possible, but I don't know if we've come up with a concrete method yet.

**Comment by markspanbroek** [comment]
Good question @emizzle, thanks. I'm not sure whether we've decided on a specific scheme yet for the erasure coding, but I know that eventually we want to enable the use case where a dataset doesn't fit in its entirety on a single host. So even though the current implementation downloads everything, that is likely to change in the future.

**Comment by dryajov** [comment]
> Good question @emizzle, thanks. I'm not sure whether we've decided on a specific scheme yet for the erasure coding, but I know that eventually we want to enable the use case where a dataset doesn't fit in its entirety on a single host. So even though the current implementation downloads everything, that is likely to change in the future.

Correct, the current implementation is a placeholder and we shouldn't develop functionality around it. As for how to know which data the slot needs to download, we know this by the offset of blocks/bytes that we want to download. This probably requires more details and I'll try to capture it ASAP in a different issue.
