### ISSUE TITLE
[BUG] Unable to start client contract interactions when connecting to a geth node

### ISSUE THREAD

**Issue by benbierens** [codex-storage/nim-codex#398]
Calls to '/api/codex/v1/sales/availability' or '/api/codex/v1/storage/request/' cause
'Unable to start client contract interactions:  error="unable to decode return value as (seq[RequestId],)"'
when using a geth node instead of hardhat.

See attached log files for details:
[MarketplaceExample_FAILED.log](https://github.com/status-im/nim-codex/files/11272133/MarketplaceExample_FAILED.log)
[MarketplaceExample_000000.log](https://github.com/status-im/nim-codex/files/11272131/MarketplaceExample_000000.log)
[MarketplaceExample_000001.log](https://github.com/status-im/nim-codex/files/11272132/MarketplaceExample_000001.log)

Off-topic:
Given that this is the very first, proper issue that is discovered using the distributed-testing setup, I hope you'll permit me to include in this message, the following:
Awww Yeahh!!
![image](https://media2.giphy.com/media/10hO3rDNqqg2Xe/giphy.gif?cid=ecf05e472zsg34h6ivcatwwshbiifmv6gxybji7iclij9sdb&rid=giphy.gif&ct=g)

**Comment by markspanbroek** [comment]
Seems that results from calls to the smart contract are not deserialized properly. Likely a difference between Hardhat and Geth. There are two similar errors in the logs:

```
ERR 2023-04-19 09:37:52.332+00:00 Proving failed                             tid=7 msg="unable to decode return value as (MarketplaceConfig,)"
```
```
ERR 2023-04-19 09:37:52.334+00:00 Unable to start client contract interactions:  topics="codex node" tid=7 error="unable to decode return value as (seq[RequestId],)"
```

Could be an bug in `nim-ethers` or `nim-contract-abi`.

**Comment by markspanbroek** [comment]
After further investigation, I don't think it's a serialization issue. I tried reproducing the errors with a Geth private network, but couldn't. 

I only see these errors when running against a Geth private network that does not have the Marketplace contract deployed. So this could be a problem in the testing environment. Either the contract address is not passed correctly to the codex node, or the blocks containing the deployment of the contract have not reached the companion Geth nodes yet when the codex node is started.
