### ISSUE TITLE
[BUG] Nodes don't connect

### ISSUE THREAD

**Issue by benbierens** [codex-storage/nim-codex#399]
Steps:
- Set up a codex node as bootstrap node.
- Set up 2 more, connect those to the bootstrap node.
- Wait (1 minute, 2 minutes, 15 minutes...)
- Turn off the bootstrap node
- Upload file to one remaining node
- Try and download it from the other
-> Download will timeout. The nodes don't know each other.
(If one were to connect the two nodes manually with the /connect endpoint, the download does work. There's no networking issue in the test setup preventing this connection.)

Logs:
[BootstrapNodeDisappearsTest.zip](https://github.com/status-im/nim-codex/files/11273539/BootstrapNodeDisappearsTest.zip)

**Comment by dryajov** [comment]
This is expected, nodes don't connect unless required, which is triggered during download. So the bootstrap node is needed at least during download startup.

**Comment by dryajov** [comment]
We can potentially augment this with random DHT walks on startup/periodically, to allow keeping the DHT tables up to date...

**Comment by benbierens** [comment]
This issue seems to break down into two other issues:
NAT is required for nodes to properly announce their addresses over the DHT: https://github.com/status-im/nim-codex/issues/166
Without NAT, tests have used the `/connect` REST API call to set up the nodes. It appears to not update libp2p's peer info correctly: https://github.com/status-im/nim-codex/issues/406

More on this as it develops!
