### ISSUE TITLE
DHT random walk

### ISSUE THREAD

**Issue by dryajov** [codex-storage/nim-codex#400]
Currently, DHT lookups are only triggered when lookups are performed, which only happens during download. We need to add a periodic random walk that keeps the DHT primed with hosts.

Fixes #399

**Comment by benbierens** [comment]
Please check if this is already implemented in libp2p-dht.
https://github.com/status-im/nim-libp2p-dht/blob/main/libp2pdht/private/eth/p2p/discoveryv5/protocol.nim 
Go to line 850.
randomQuery() appears to be part of a 5-minute refreshLoop()

**Comment by dryajov** [comment]
Feature is implemented after all
