### ISSUE TITLE
Docker CI Update

### ISSUE THREAD

**Issue by benbierens** [codex-storage/nim-codex#412]
We've had a basic docker CI for a while, but it's no longer sufficient and it needs a good update.
Please work with this branch for this issue: https://github.com/status-im/nim-codex/tree/docker-marketplace-update

# Docker Hub Account
We need a docker-hub account that's owned by the Codex team. We have been using my account 'thatbenbierens' for the AMD images. And we've using Eric's 'emizzle' for the ARM images. This is getting too messy.
- [x] Set up a docker-hub account for the team
- [x] Make sure credentials are available and can be found in the future by those who might need them
- [x] Update the docker secrets in the settings of this repository
- [x] Update the workflows/docker.yml to use the new hub account

# ARM Support
We've tried building ARM64 images 'the normal way' using github's emulators. It turns out some of our nim-code doesn't work in arm-emulation (issue is known, ticket is filed). To work around this, we've been building the ARM images on Eric's dev machine, and by using buildjet: https://buildjet.com/for-github-actions/docs/guides/migrating-to-arm (This is a paid service, but it gives plenty of free trial time to get started.)
- [x] Determine how we're going to build ARM images. (use buildjet? use another native ARM runner?)
- [x] Update the workflows/docker.yml to build ARM images this way.
- [x] Bonus points: If we can build a single multi-architecture docker image, that would be ideal but it's not required.

# Codex Contracts Repository
This isn't the only repo we need docker images from. Once the above two topics are solved, we should apply the same approach to Codex-Contracts-Eth. Dockerization branch is here: https://github.com/status-im/codex-contracts-eth/tree/docker
- [x] Apply same docker-image-building approach to Codex-Contracts-Eth

**Comment by jakubgs** [comment]
If you intend to build on Jenkins then one possibility is the RX lines from Hetzner with Ampere Altra Q80-30 processors:
https://www.hetzner.com/dedicated-rootserver/matrix-rx

Bit expensive, but one won't hurt that much, and might be used by Nimbus and possibly Desktop as well.

**Comment by veaceslavdoina** [comment]
Some already discussed options
| Option                                                                  | Price, $                      | Cost, $/1h/1d/1m       | Comment                        |
| ----------------------------------------------------------------------- | ----------------------------- | ---------------------- | ------------------------------ |
| [BuildJet](https://buildjet.com/for-github-actions/docs/about/pricing)  | `2 vCPU/3 GB = 0.004 / min`   | `0.24 / 5.76 / 178.56` | buildjet-2vcpu-ubuntu-2204-arm |
| [AWS CodeBuild](https://aws.amazon.com/codebuild/pricing/)              | `2 vCPU/3 GB = 0.00385 / min` | `0.23 / 5.52 / 171.12` | Frankfurt (arm1.small)         |
| [AWS EC2](https://aws.amazon.com/ec2/pricing/on-demand/)                | `2 vCPU/8 GB = 0.092 / h`     | `0.09 / 2.21 /  68.45` | Frankfurt (m6g.large)          |
| [Hetzner RX170](https://www.hetzner.com/dedicated-rootserver/matrix-rx) | `80 CPU/128 GB = 220 /m`      | `0.30 / 7.01 / 220.00` |                                |

| BuildJet          | AWS CodeBuild    | AWS EC2            | Hetzner         |
| ----------------- | ---------------- | ------------------ | --------------- |
| `32 vCPU / 48 GB` | `8 vCPU / 16 GB` | `32 vCPU / 128 GB` | `80 CPU/128 GB` |
| `2,856.96 $/m`    | `781.2 $/m`      | `1,472 $/m`        | `220 $/m`       |

BuildJet with `1h` everyday will costs us `7.44$/m`. If something similar will be for Codex-Contracts-Eth we may cover all that with just `15$/m`. It looks not so expensive if we need it ASAP and later we may review other options.

Jakub mentioned that we may consider to use a common CI and as total load will be higher, Hetzner looks wery well for that. But we should consider that it will require to move existing workflow out from GitHub Actions.

**Comment by dryajov** [comment]
My preferred order of priority is 1) get it working first, 2) make it faster and cheaper - if we can get both at the same time without much compromises (in terms of blocking other work) then even better. Whatever we choose, cost will be secondary at the current scale.

**Comment by veaceslavdoina** [comment]
@benbierens, a short status about the task
 1. We have a [DockerHub Organization for Codex](https://hub.docker.com/u/codexstorage).
 2. We started to use BuildJet - let see how it works and costs.

 3. Workflow in the [branch](https://github.com/codex-storage/nim-codex/tree/docker-marketplace-update) was updated and now we can build separate images and a common one via manifest update
    ```bash
    # On commit
    sha-984101b
    sha-984101b-linux-arm64
    sha-984101b-linux-amd64

    # On tag
    latest
    0.0.1
    0.0.1-linux-arm64
    0.0.1-linux-amd64
    ```
   Tag `latest` is added only on relase, by tags.

 4. Workflow was tested and [images](https://hub.docker.com/repository/docker/codexstorage/nim-codex/tags) can be run on Linux x86-64/arm
    ```bash
    # Common
    docker run --rm codexstorage/nim-codex:sha-984101b
    
    # Specific
    docker run --rm codexstorage/nim-codex:sha-984101b-linux-amd64
    docker run --rm codexstorage/nim-codex:sha-984101b-linux-arm64
     ```

 5. Once we are ready for merge, I will update the token in the GitHub Actions.

 6. Some organizational stuff is still in progress

**And the following notes for future elaboration**
 1. If we would like to leave just common images it will be required to use GA Artifacts Upload/Download or maybe a workaround with just deleting platform specific image.
 2. We should check labels we are adding.
 3. We have some conditional steps for but workflow is not triggered by that event.
    ```yaml
    - name: Docker - Push to Docker registry
      if: github.event_name != 'pull_request'
      id: push
      uses: docker/build-push-action@v4
      ```

**Comment by jakubgs** [comment]
Aren't you essentially repeating the same thing for `arm64` and `amd64`? Can't we use the `matrix` as `nimbus-eth2` does?
https://github.com/status-im/nimbus-eth2/blob/40253a76ddcfd2aa29ef662bb8ee61306093fd1c/.github/workflows/ci.yml#L28C7-L35

**Comment by veaceslavdoina** [comment]
You are right, and it was my first consideration but it will add additional conditions and with multiple platforms can be tricky to maintain?
<details>
<summary>linux-amd64</summary>

```yaml
  linux-amd64:
    name: Linux amd64
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    env:
      PLATFORM: linux/amd64
      SUFFIX: linux-amd64
```
</details>
<details>
<summary>linux-arm64</summary>

```yaml
  linux-arm64:
    name: Linux arm64
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    env:
      PLATFORM: linux/arm64
      SUFFIX: linux-arm64
```
</details>

Thanks, let me check how it will looks like.

**Comment by jakubgs** [comment]
In general platform specific edge cases should be handled in build configuration, like a `Makefile` not in CI.

**Comment by veaceslavdoina** [comment]
@jakubgs, [new workflow version](../blob/docker-marketplace-update/.github/workflows/docker.yml) is almost twice shorter and works fine, thanks.

@benbierens, repository secretes were updated. Are we ready for the merge - [Docker marketplace update #419](#419)?

**Comment by veaceslavdoina** [comment]
Now we have builds for the `codex-contracts-eth` as well - https://github.com/codex-storage/codex-contracts-eth/pull/56 and images accessible on the [DockerHub](https://hub.docker.com/r/codexstorage/codex-contracts-eth/tags).

**Comment by veaceslavdoina** [comment]
All mentioned points were implemented and CI related changes were merged.

Some updates to the Docker images builds will be done in a separate request `-d:codex_enable_api_debug_peers=true`.

We can consider that task as done.

**Comment by veaceslavdoina** [comment]
[Arm-based hosted runners are coming to GitHub Actions! 🚢 #73040](https://github.com/orgs/community/discussions/73040)
