### ISSUE TITLE
Feature request - Add common units support for Codex configuration

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/nim-codex#466]
**Is your feature request related to a problem? Please describe.**
It is just a suggestion to make Codex configuration setting and reading easier.

**Describe the solution you'd like**
We should be able to pass common units to Codex app via CLI, Env and Config
```bash
# CLI
codex --block-ttl=1m
codex --block-ttl=1h
codex --block-ttl=1d

# Env
export CODEX_BLOCK_TTL=60m
codex
```

Should we also add Month and Year support as well?

**Describe alternatives you've considered**
As for now, we can set just seconds
```bash
codex --block-ttl=1
```

**Additional context**
1. Does `--storage-quota` have support of `k`, `m`, `g`, `t`, `p`?
   ```shell
    codex --storage-quota=1m
    Error while processing the storage-quota=1m parameter: invalid integer: 1m
    Try codex --help for more information.

    codex --storage-quota=1M
    Error while processing the storage-quota=1M parameter: invalid integer: 1M
    Try codex --help for more information.
   ```
2. Should we make it case-sensitive?

**Comment by elcritch** [comment]
Ref's https://github.com/status-im/nim-stew/blob/8bb07fac39f5e774fb9813382c7aaed93bcb1cce/stew/shims/parseutils.nim#L5 and https://github.com/codex-storage/nim-codex/pull/346/files

Though I'm not seeing where / how it's plumbed into confutils, but I can dig into that a bit.

**Comment by elcritch** [comment]
Ah, now I get understand. I thought @veaceslavdoina was saying that we already* had that feature, but it looks like there's a parsing util but we'd need to plumb it into confutils. 

That shouldn't be too bad. I'll have to ponder it a little bit and maybe get to it later this week.

**Comment by dryajov** [comment]
> plumb it into confutils

Confutils supports custom types mapping/parsing out of the box. For example, here is how we parse `MultiAddress` strings - https://github.com/codex-storage/nim-codex/blob/master/codex/conf.nim#L291, we should only need a similar method for size parsing. 

It might be useful to add it natively to confutils, but I'm not 100% sure?

**Comment by dryajov** [comment]
> > Ah, now I get understand. I thought @veaceslavdoina was saying that we already had that feature, but it looks like there's a parsing util but we'd need to plumb it into confutils.
> 
> @elcritch, yes - probably I've miss the point that [PR](https://github.com/codex-storage/nim-codex/pull/346/files) you mentioned was not merged.

Yeah, this is now part of the latest stew, it just needs to be wired in codex (or potentially confutils, but that might be a more long term solution).

**Comment by elcritch** [comment]
Ok good to know! It seems to best route is to adjust the types in `codex/conf.nim` and create the serialization proc's to use the new stew utils. Should be pretty easy for sizes, but time will require a new Stew PR probably.

@veaceslavdoina could you look at the `parseSize` function and see if those formats are good? As in, does the lowercase / uppercase seem fine to you?

**Comment by veaceslavdoina** [comment]
### Time

I don't know how it works but seeing the following
**Nim:** [std/times](https://nim-lang.org/docs/times.html)
**Rust:** [chrono::format::strftime](https://docs.rs/chrono/latest/chrono/format/strftime/index.html#)
**C++:** [strftime](https://en.cppreference.com/w/c/chrono/strftime)

| Language | Second | Minute | Hour | Day | Month | Year   |
| -------- | ------ | ------ | ---- | --- | ----- | ------ |
| Nim      | `s`    | `m`    | `H`  | `d` | `M`   | `yyyy` |
| Rust     | `S`    | `M`    | `H`  | `d` | `m`   | `Y`    |
| C++      | `S`    | `M`    | `H`  | `d` | `m`   | `Y`    |

It is about time parsing, but we can use probably that information as an input
```
s - seconds
m - minutes
h - hours
d - days
```

Not sure if we need months and years
```
M - month
y - year
```
Because we can easy set `--block-ttl=30d` or `--block-ttl=365d`

If we will decide to make that case insensitive
```
s = S - seconds
m = M - minutes
h = H - hours
d = D - days
```
It means that if we will consider at some point to add `M - month` support it will introduce breaking changes.


### Size

[Wikipedia - Multiple-byte units](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units)

> **Nomenclature for these systems has been the subject of confusion.** Systems based on powers of 10 reliably use standard SI prefixes (kilo, mega, giga, ...) and their corresponding symbols (k, M, G, ...). Systems based on powers of 2, however, might use binary prefixes (kibi, mebi, gibi, ...) and their corresponding symbols (Ki, Mi, Gi, ...) or they might use the prefixes K, M, and G, creating ambiguity when the prefixes M or G are used.

My view is the following
 1. We should use just a single format and it should be binary prefixes (1024) - `k = K = KiB`
 2. They should be case insensitive - `b = B`, `k = K`, `m = M`, `g = G`, `t = T`, `p = P`

But all that just an idea how to make it less ambiguous and easy to use.

**Comment by elcritch** [comment]
Thanks for the detailed response @veaceslavdoina ! It'll be helpful. 

@dryajov I missed your earlier comment regarding adding the parse method, but yes that's my thoughts too. It'd be nice to add to confutils natively, but that seems like a bit of a detour for now.. I think use it locally for a while and then add it upstream? There might be small surprises we'll want to learn about when using units from the CLI? Particularly casing and 1000 vs 1024 based size units, etc.

**Comment by dryajov** [comment]
> I think use it locally for a while and then add it upstream? 

Yeah, figuring out the best UX for this definitely requires some heuristics. Lets keep it simple for now tho :)

**Comment by veaceslavdoina** [comment]
@elcritch, thank you for the implementation 🚀
