### ISSUE TITLE
Orphaned availabilities 

### ISSUE THREAD

**Issue by AuHau** [codex-storage/nim-codex#468]
I am not sure if it is a problem or not, but I have realised that Availabilities will be most probably never "used-up" as most probably there will be some capacity left in them (even very little) for which there won't be the proper Request's size (and other parameters) fit.

Is it a problem? WDYT? @markspanbroek @emizzle

**Comment by markspanbroek** [comment]
The small leftovers should probably be merged with other compatible availabilities (e.g. with the one it originally split off from when it returns (#410))

**Comment by emizzle** [comment]
This is a good point. I think we could have availabilities under a certain size (cli param-defined perhaps) try to merge with compatible exisiting availabilities (as @markspanbroek mentioned above) We would also need to consider attempting a merge when new availabilities are added, as there may still be availability dust floating around. As part of #455, there will be a signal triggered when availabilities are added, which could be utilised here.

> (e.g. with the one it originally split off from when it returns (https://github.com/codex-storage/nim-codex/issues/410))
I'm not sure there is a "splitting" of availabilities. The current implementation simply reduces the availability's size as blocks are downloaded, then marks it unused after download. Once that availability gets to a certain size, we could then attempt to merge that availability with other availabilities that have looser (or equal) availability requirements.
