### ISSUE TITLE
Slot queue test fails occasionally

### ISSUE THREAD

**Issue by markspanbroek** [codex-storage/nim-codex#494]
This test fails occasionally (once every 10 runs or so):

https://github.com/codex-storage/nim-codex/blob/1d161d383ec2738cdc3a0eac16e8b0788f218edb/tests/codex/sales/testsales.nim#L178

I couldn't see anything obviously wrong, could you take a look @emizzle?

**Comment by emizzle** [comment]
Locally, in master, I was able to successfully run `testsales` 20 times with no errors, and `make test` 10 times with no errors.

There also doesn't seem to be any errors in CI relating to this.

Are you definitely still seeing this error?

**Comment by markspanbroek** [comment]
It's a tough one to reproduce for some reason. On my older laptop I see the error quite frequently, but on my newer desktop see it much less frequently. I was able to reproduce it on CI as well, but it did not occur as often as I expected: https://github.com/codex-storage/nim-codex/actions/runs/6010028817/job/16300630141?pr=539#step:4:2933

```
testsales.nim(277, 28): Check failed: eventuallyCheck itemsProcessed.len == request.ask.slots.int
```

I had to run the test 10000 times :smile:  #539
