### ISSUE TITLE
Amount of active Slots that host can host is limited to SlotQueue's `maxWorkers` (default 3)

### ISSUE THREAD

**Issue by AuHau** [codex-storage/nim-codex#532]
After merging Proving and Sales state machines in https://github.com/codex-storage/nim-codex/pull/469, the sale state machine's process finishes **only after the whole request's duration is passed and a request is paid out** (if not taking into consideration the error states and other "edge-cases").

This is a problem because currently, the SlotQueue works in a way that it delegates the Sales process for the chosen Slot to pool of workers (default is 3) and **it blocks the worker until the Sales process is finished**, which is now much longer then it used (before it was till Slot is filled and then for proving phase it was handed out to the other state machine). So essentially, this limits the number of concurrently hosted slots to the number of workers.

**Comment by emizzle** [comment]
The `processed` future could be completed at an earlier state. Currently it's completed in sales.onCleanUp, but a different callback could be created, that completes the Future at an earlier state.

**Comment by AuHau** [comment]
Agree, the question is, at what stage? I guess the `filled` state could be a good place to have it.

**Comment by emizzle** [comment]
Yep, I think `Filled` would be the most ideal place, as this indicates that the slot processing, both downloading and initial proof generation, as well as filling contract calls, have been completed.
