### ISSUE TITLE
Crash when want-block fails or expires

### ISSUE THREAD

**Issue by benbierens** [codex-storage/nim-codex#613]
![image](https://github.com/codex-storage/nim-codex/assets/39762930/7f94940e-fa1a-42ff-96ac-1d60b3d21d01)

Observed in: sha-80e2ef

**Comment by benbierens** [comment]
When the block handle created `pendingblocks.nim:60` expires with a timeout, all awaiters should raise a catchable error.
This error is caught in `pendingblocks.nim:72` and logs the trace statement "Pending WANT failed or expired".
This error is caught in 'engine.nim:165` and *should* log the trace statement "Error block handle, disconnecting peer".
The engine trace statement is present in the crash log, but was not present when recreating the block-expiration timeout. In the recreation attempt, the application didn't crash. This suggests that the `monitorBlockHandle` method in engine.nim may be responsible for the crash.
Open question: How is it possible that the failure of the block handle with a timeout exception causes one awaiter to respond, but not the other?

**Comment by markspanbroek** [comment]
It crashes in `binderror.nim` in questionable. There's still an old version of questionable in codex, which doesn't have this fix: https://github.com/codex-storage/questionable/pull/46. Updating to latest questionable will most likely fix this issue.

**Comment by benbierens** [comment]
Good find!
