### ISSUE TITLE
Block not found in local store (404)

### ISSUE THREAD

**Issue by q9f** [codex-storage/nim-codex#674]
**Describe the bug**
Following the two-node tutorial, I started two nodes, peered them and uploaded a file to node 1 but could not retrieve it from node 2.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run node 1
   `codex --log-level=trace --data-dir=/home/user/.cache/codex/0 --listen-addrs=/ip4/0.0.0.0/tcp/0`
2. Get SPR
    `curl http://127.0.0.1:8080/api/codex/v1/debug/info | jq ".spr"`
3. Run node 2 connecting to node 1 
   `codex --log-level=trace --data-dir=/home/user/.cache/codex/1 --listen-addrs=/ip4/0.0.0.0/tcp/0 --api-port=8081 --disc-port=8091 --bootstrap-node=spr:CiUIAhIhAwsu7u01NoQObuz7ekIli31VEMpsIIBR5PQadUw5enNEEgIDARo8CicAJQgCEiEDCy7u7TU2hA5u7Pt6QiWLfVUQymwggFHk9Bp1TDl6c0QQwd6TrQYaCwoJBH8AAAGRAh-aKkYwRAIgIRaFKKx0nKy3hfuoOC6XUBbYy6ZGEwu6c-qTTtdTOa8CIGhWt_fIECTjH623mJpJs1W1K0WTl4YWfFyoqoOy2S9u`
4. Ensure nodes are connected (they are)
   `curl http://127.0.0.1:8081/api/codex/v1/debug/info | jq ".table.nodes"`
5. Upload file to node 1
   `curl -vvv -H "content-type: application/octet-stream" -H Expect: -T /home/user/Desktop/q9f_a_germanic_pagan_christmas_tree_on_a_barren_rocky_lunar_sur_26764872-9acc-44b3-8df7-9a2113b81fe9.png "127.0.0.1:8080/api/codex/v1/data" -X POST`
6. Retreive CID `zDvZRwzkx6dynxjqQittMgTKpMyRREM5Taamj8w9yHFi5Cd4jHHB`
7. Download the block from node 2
   `curl -vvv "127.0.0.1:8081/api/codex/v1/data/zDvZRwzkx6dynxjqQittMgTKpMyRREM5Taamj8w9yHFi5Cd4jHHB" --output /home/user/zDvZRwzkx6dynxjqQittMgTKpMyRREM5Taamj8w9yHFi5Cd4jHHB.png`
8. Get 404

```
DBG 2024-01-15 10:18:53.364+01:00 Received request                           topics="codex" tid=1133849 peer=127.0.0.1:50294 meth=GET uri=/api/codex/v1/data/zDvZRwzkx6dynxjqQittMgTKpMyRREM5Taamj8w9yHFi5Cd4jHHB
DBG 2024-01-15 10:18:53.364+01:00 Serving API request                        topics="codex" tid=1133849 peer=127.0.0.1:50294 meth=GET uri=/api/codex/v1/data/zDvZRwzkx6dynxjqQittMgTKpMyRREM5Taamj8w9yHFi5Cd4jHHB path_params="(table: {\"cid\": @[\"zDvZRwzkx6dynxjqQittMgTKpMyRREM5Taamj8w9yHFi5Cd4jHHB\"]})" query_params="(table: {:})" content_body=none(ContentBody)
TRC 2024-01-15 10:18:53.364+01:00 Checking network store for block existence topics="codex networkstore" tid=1133849 cid=zDv*d4jHHB
TRC 2024-01-15 10:18:53.365+01:00 Sent bytes                                 topics="codex restapi" tid=1133849 cid=zDv*d4jHHB bytes=0
DBG 2024-01-15 10:18:53.365+01:00 Received error response from handler       topics="codex" tid=1133849 status=404 meth=GET peer=127.0.0.1:50294 uri=/api/codex/v1/data/zD
vZRwzkx6dynxjqQittMgTKpMyRREM5Taamj8w9yHFi5Cd4jHHB error="(status: 404 Not Found, message: \"Block not found in local store\", contentType: \"text/html\")"
```

I am, however, able to download the file from node 1.
 
**Expected behaviour**
According to the docs, I should be able to retrieve the file from node 2.

**Screenshots**
![2024-01-15-102232_3440x1440_scrot](https://github.com/codex-storage/nim-codex/assets/58883403/8444582c-d09d-47f0-a433-b608a4e5d053)

**Environment:**
 - OS: Arch Linux 6.6.10-arch1-1
 - Version: untagged build
 - Tag/Commit: 8b12934fe242381df8a65ac6afd32c6e171dac4a
 - Arch: x86_64

**Additional context**
The guides at https://docs.codex.storage/ are very outdated, I had to dig a bit to get all config and API requests to work.

**Comment by benbierens** [comment]
Hi Afri! Very cool you're taking a look at the project. Yeah, the docs.codex.storage is a bit out of date. A safer bet is to look at the openapi.yaml, here:

https://github.com/codex-storage/nim-codex/blob/8b12934fe242381df8a65ac6afd32c6e171dac4a/openapi.yaml#L379C25-L379C25

By default, `curl -vvv "127.0.0.1:8081/api/codex/v1/data/<CID>"` will only fetch data from the node's local store. If you want to download from the network, append `/network`, like so:
`curl -vvv "127.0.0.1:8081/api/codex/v1/data/<CID>/network"`

See if that does it.

**Comment by q9f** [comment]
Ah, beautiful. That worked! Thanks!

![2024-01-15-113040_3440x1440_scrot](https://github.com/codex-storage/nim-codex/assets/58883403/1d1ee9da-6488-4e26-ad0d-5e2e67b27ee0)

**Comment by AuHau** [comment]
You can also find "user-friendy" version of the OpenAPI on [api.codex.storage](https://api.codex.storage)  ;-)

**Comment by q9f** [comment]
Ah-ha! I promise I clicked everything on your website but that was not linked anywhere ;)

**Comment by AuHau** [comment]
Yeaaah, it is indeed not present on any websites, only on the Readme atm. I need to fix that; thanks for the heads-up! 👍
