### ISSUE TITLE
chore: nim-libp2p path update

### ISSUE THREAD

**Issue by kaiserd** [codex-storage/nim-codex#740]
nim-libp2p moved from the status github org to the Vac org: https://github.com/vacp2p/nim-libp2p

This issue tracks the effort of updating respective paths in Codex.

**Comment by gmega** [comment]
The main repos that use libp2p in Codex are:

* nim-codex-dht: https://github.com/codex-storage/nim-codex-dht/pull/91
* codex itself: https://github.com/codex-storage/nim-codex/pull/743

There's also the [old DAS DHT emulator](https://github.com/codex-storage/das-dht-emulator) but I don't think that anyone is using it anymore.

I'll let @dryajov chip in but unless there's anything else we just need to merge those and can then close the issue.

**Comment by dryajov** [comment]
@gmega Looks good, I think this are the only places that use libp2p so far.

**Comment by gmega** [comment]
Ok, looks like this is done. Gonna close it.
