### ISSUE TITLE
Branch for testnet

### ISSUE THREAD

**Issue by gmega** [codex-storage/nim-codex#747]
As we approach our launch date, we need to refine our practices so that we create a (more) stable branch for testnet releases. We have a number of options:

* use **master** for stable (testnet-ready) code and a **dev** branch for newer stuff ([gitflow style](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow));
* use **stable** and **unstable** like other projects @ status/logos/vac like [libp2p](https://github.com/vacp2p/nim-libp2p) and [nimbus](https://github.com/status-im/nimbus-eth2) do.

These are clearly not the only options and we can make this as complicated as we want. :slightly_smiling_face: So, what color should the bikeshed be?

**Comment by benbierens** [comment]
I vote for option 1: A stable master that is "released" to the test-net, and a dev where we can go relatively crazy.

**Comment by tbekas** [comment]
Same with me, both options work. I'm more used to option 1, but option 2 is also fine.

**Comment by AuHau** [comment]
I like option 1 more, but could do also with option 2.

My question is though, is this something temporary for the testnet release? Or will this become our dev-flow "for ever"?

**Comment by emizzle** [comment]
I'm fine with either but I think option 2 provides a bit more leeway in terms of branch usage, ie we may need a stable branch at some point that isn't used for the testnet. If we instead decide to cut a branches for different use cases, it can become difficult to maintain those branches and also understand if they're meant to be stable or not.

**Comment by gmega** [comment]
OK, after some discussion, this is what came out.

**Rolling development branch.** We will rename `master` to `develop`, and this will become our development branch. PRs should be merged into `develop`. The code in `develop` should always stable enough that it passes tests and integration tests.

**Release branches.** Each release will be forked off of master as a release branch; i.e., `release/katana`. Release branches will be subjected to intensive testing and bugfixing. We must ensure that any critical bug fixes are cherry-picked into `master`. Once a release branch is deemed stable enough, it is released into a testnet.

Because `develop` is allowed to continue evolving, we cannot erase the release branch for as long that release lives. In principle, this means the branch should live, at the very least, all the way to a release being retired from mainnet. In practice, we probably will never erase a release branch as it contains the commit history of that release.

We typically will not support multiple running releases. I therefore expect we will have at most one release running on mainnet, and the one that follows it running on a testnet. On average, therefore, we should have $3$ active branches:

<div style="display: flex; justify-content: center; padding: 10px 0 30px 0">
    <img src="https://github.com/codex-storage/nim-codex/assets/1887335/895a93fc-765e-4e9f-a973-9756badbe25d" width="300px"/>
</div>

**Comment by gmega** [comment]
@veaceslavdoina suggested we don't rename master. I'm fine with that, provided it's understood that `master` is not a stable branch.

**Comment by gmega** [comment]
OK, last amendment: we agreed that naming the release branches after major versions made more sense than using release names as versions are easier to place on a timeline than arbitrary names. So the first release branch will be called, rather uncreatively, `release/1.x`.

**Comment by gmega** [comment]
Changed testnet branch name to release/0.1, as per @AuHau's reasoning:

"I would expect that we go 0.x until the mainnet launch which I would expect to be the 1.0? Also what is the expected lifespan of this branch? I was more expecting like 0.1 which would be closed once released to testnet and then next 0.2 (or whatever version) would be drafted from master when we say that we want to do another release..."

That indeed makes more sense than my initial take that we'd take this branch all the way to mainnet when we don't even have a stable network protocol. 

Another point regards the use of semver:

* we'll use major versions to denote breaking changes to network protocols;
* the Codex REST API (and other APIs that we may expose) should be versioned separately.

**Comment by emizzle** [comment]
Based on another several rounds of discussions, we have settled on:
1. Use branch naming convention: `release/<major>` or `release/<major.minor>`
2. Have `master` as the unstable branch
3. Bugs fixes are to be done in `master` only, then backported to the release branches
4. Each release will be tagged, so that a github release can be created, triggering CI
5. Once a new release branch is created, and before it is deployed to testnet (via a release), we will likely need to deploy it to devnet to test.

**Comment by AuHau** [comment]
@emizzle I think this can be closed no?
