### ISSUE TITLE
NAT traversal

### ISSUE THREAD

**Issue by elcritch** [codex-storage/nim-codex#753]
Preliminary Tasks:
- [x] investigate libp2p's capabilities and [go through @dryajov's branch](https://github.com/codex-storage/nim-codex/pull/763);
- [x] run two-NATted-one-relay setup with Docker/iptables based off of [the work from the rust-libp2p folks](https://github.com/marten-seemann/docker-nat-simulator) and check if hole punching works.

Follow-up Tasks:
- [x] figure out what to do about the DHT;
- [x] figure out how to do rendezvous server discovery.

Documents:

* Discussion along with a proposal for a full-fledged solution: [here](https://hackmd.io/UxYaQ3dqS1CUU8pxO6-PuQ)
* Rollout plan: [here](https://hackmd.io/p6fL4TEkTgGljTBmWfXicw)

**Comment by elcritch** [comment]
Notes:
- nim-libp2p supports AutoNat protocol that allows others to check if your IP is able to be reached publicly
- libp2p spec supports nat [hole punching](https://docs.libp2p.io/concepts/nat/hole-punching/)
  + nim-libp2p appears to have support for relay nodes
  + [ ] determine if nim-libp2p supports hole punching 



Background info: 
- How nat traversal works: https://tailscale.com/blog/how-nat-traversal-works
- NAT traversal research: https://ieeexplore.ieee.org/document/5235278

**Comment by elcritch** [comment]
Dmitry: It should be relatively simple to setup some emulation (test network) in a cloud, either with a full-fledged networking distro, and testing against that or some emulator software.

**Comment by arnetheduck** [comment]
both waku and nimbus implement nat traversal already, can copy from there

**Comment by cskiraly** [comment]
@elcritch , if you are dealing with NAT, be aware that the DHT code has some specific parts related to IP address discovery.

Check these: 
- https://github.com/codex-storage/nim-codex-dht/blob/master/codexdht/private/eth/p2p/discoveryv5/ip_vote.nim
- https://github.com/codex-storage/nim-codex-dht/blob/229931711634488201fb74f52d4ba6d96d1a9759/codexdht/private/eth/p2p/discoveryv5/protocol.nim#L973

**Comment by gmega** [comment]
Adding a link to @dryajov's PR: https://github.com/codex-storage/nim-codex/pull/763

**Comment by AuHau** [comment]
Btw. there is old issue here: https://github.com/codex-storage/nim-codex/issues/166 
Maybe it should be closed?

**Comment by gmega** [comment]
This is needed for #782

**Comment by gmega** [comment]
Work in progress for the NAT test environment [here](https://github.com/gmega/codex-nat-env/).

**Comment by gmega** [comment]
Gonna close this and open a new issue with the actual rollout plan.
