### ISSUE TITLE
OpenAPI mismatches

### ISSUE THREAD

**Issue by benbierens** [codex-storage/nim-codex#755]

**Comment by AuHau** [comment]
@benbierens since it is in `Done&Merged` in the project, I assume we can close this. If not please reopen.

**Comment by AuHau** [comment]
I don't know, but I have also discovered some inconsistencies which I have fixed here: https://github.com/codex-storage/nim-codex/pull/886

I guess we just need to play with the API more to discover more issues ;-)

**Comment by benbierens** [comment]
I can just throw away my customizations in the dist-tests and run only with the openAPI spec. Then we will know very quickly if it's correct! :D
