### ISSUE TITLE
Create a binary release in the `nim-codex` repo

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#779]
Binary release to be create inside of the `nim-codex` repo. This binary will be downloaded by workshop participants to be used in the workshop.

I know this is going to bring up the versioning discussion. I remember that we had this discussion at some point in time regarding codex binary version vs REST api version vs network version (perhaps @AuHau you remember?)

**Comment by veaceslavdoina** [comment]
[Add Release workflow for Codex #749](749) - is that related or a successor?

**Comment by emizzle** [comment]
Closing in favour of #749
