### ISSUE TITLE
Wifi router backup

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#781]
Purchase wifi router and SIM dongle (or maybe one that's integrated) that supports around 100 simultaneously connected devices. This can be used as a backup if the workshop venue wifi starts to lag/fail with a lot of connections.

**Comment by veaceslavdoina** [comment]
I have first two devices and also worked slightly with the Mikrotik and UniFi

| # | Device                                                                                                                      | Wi-Fi       | Moble | Clients | Coverage | Price    |
| - | --------------------------------------------------------------------------------------------------------------------------- | ----------- | ----- | ------- | -------- | -------- |
| 1 | [NETGEAR Nighthawk M6 Pro (MR6450)](https://www.netgear.com/uk/home/mobile-wifi/hotspots/mr6450/)                           | 4, 5, 6, 6E | 5G    | 32      | ?        | ~ 1000 € |
| 2 | [ZTE MU5120](https://www.ztedevices.com/en/products/mobile-internet/5g-mbb/mu5120.html)                                     | 4, 5, 6     | 5G    | 32 + 32 | ?        | ~ 300 $  |
| 3 | [Mikrotik Chateau 5G ax](https://mikrotik.com/product/chateau_5g_ax)                                                        | 4, 5, 6     | 5G    | ?       | ?        | ~ 595 $  |
| 4 | [UniFi Dream Router](https://eu.store.ui.com/eu/en/pro/category/cloud-gateways-wifi-integrated/products/udr?variant=udr-eu) | 4, 5, 5     | -     | 300     | ?        | ~ 220 €  |

- [Wi-Fi - Versions and generations](https://en.wikipedia.org/wiki/Wi-Fi#Versions_and_generations)

**Comment by emizzle** [comment]
Slava to order a UniFi Express.

Connection limits per SIM may be an issue. 
Slava to send Netgear router to Ben. Ben will try running 100+ nodes in Belgium.

**Comment by veaceslavdoina** [comment]
[UniFi Express](https://eu.store.ui.com/eu/en/pro/category/all-unifi-cloud-gateways/products/ux) arrived and the following setup was tested
![UniFi-Express](https://github.com/codex-storage/nim-codex/assets/20563034/f1fcd9b3-a24f-4b93-a5e7-1044880c7dc9)

- NETGEAR Nighthawk M6 Pro set in `IP Passthrough mode` and powered using internal battery
- UniFi Express is managed via Cloud with almost all defaults and powered via type-c port using a power bank
- NETGEAR Nighthawk M6 Pro and UniFi Express are connected via Ethernet cable
- UniFi Express get ISP Public IP on its WAN interface

<details>
<summary>images</summary>

![PXL_20240601_102506348](https://github.com/codex-storage/nim-codex/assets/20563034/3611e6b1-8aab-40ff-ac36-2f5f45900d91)
![PXL_20240601_114604099](https://github.com/codex-storage/nim-codex/assets/20563034/bc5479f1-e2e8-4f0a-9052-459a5673e51c)
![PXL_20240601_114621929](https://github.com/codex-storage/nim-codex/assets/20563034/f2d322e6-2170-4f63-a0e4-04619f01193c)
</details>

**Basic tests**
- Speed test
- Traceroute
- Public IP check
- TCP Port forwarding
- IPFS Desktop
<details>
<summary>screenshots</summary>

**Speed test**
![16323385312](https://github.com/codex-storage/nim-codex/assets/20563034/11534a65-191b-47c0-8b21-48072643e412)

**Traceroute**
<img width="848" alt="Screenshot 2024-06-01 at 15 15 12" src="https://github.com/codex-storage/nim-codex/assets/20563034/0a11c4ab-7ebf-4e5c-9c51-b4b1447e8f6b">

**Public IP check**
<img width="283" alt="Screenshot 2024-06-01 at 15 33 22" src="https://github.com/codex-storage/nim-codex/assets/20563034/9d7cdd0a-9bd6-499e-a44a-f5cee6e0a349">

<img width="1012" alt="Screenshot 2024-06-01 at 15 22 45" src="https://github.com/codex-storage/nim-codex/assets/20563034/659c7486-369a-4692-b99e-792abde2f8da">

**TCP Port forwarding**
![Screenshot (Jun 1, 2024 15 12 50)](https://github.com/codex-storage/nim-codex/assets/20563034/e089371f-315a-4554-8c98-abdc8392f12e)

**IPFS Desktop**
<img width="1503" alt="Screenshot 2024-06-01 at 14 10 47" src="https://github.com/codex-storage/nim-codex/assets/20563034/b7e86bad-5fba-4413-a788-287f5498935f">
</details>

**Quick conclusions**
- Setup is very portable and lightweight and we can use power banks and place devices in required locations
- We can pass Public IP to the Wi-Fi access point
- Moldtelecom most probably is using NAT or asymmetric routing
- TCP Port forwarding on UniFi works as expected
- We can made hundreds of connections via mobile network, but it should be tested additionally using a different approach

**Next steps**
- Check UDP Port forwarding
- Check multiple simultaneous outgoing connections
- Check multiple Wi-Fi clients

**Comment by veaceslavdoina** [comment]
### Wi-Fi coverage test

#### Environment
- Test was performed on a public stadium
- Distance was 0, 10, 20, 25 and 30 m
- AP is in direct view without any obstacles
- AP Wi-Fi `Transmit Power = High`
- Client device is Google Pixel 8 Pro with [WiFiman](https://play.google.com/store/apps/details?id=com.ubnt.usurvey) app

> **Note:** Stride length is ~ 70 cm, but they were longer then ussual and ~ 1 m.

<details>
<summary>images</summary>

**Distance - 30 m**
![PXL_20240602_073105867](https://github.com/codex-storage/nim-codex/assets/20563034/7566381f-963e-492c-9a00-b2cf082fb340)

**Equipment in the backpack on the tree**
![PXL_20240602_073113706](https://github.com/codex-storage/nim-codex/assets/20563034/ee000bbe-0d2c-4a7c-92d7-37fc48f338ef)
</details>


#### Results
| # | Time    | Distance | Wi-Fi          | Signal    | Latency | Download    | Upload      |
| - | ------- | -------- | -------------- | --------- | ------- | ----------- | ----------- |
| 1 | `10:25` | `0 m`    | `Wi-Fi 6 / 48` | `-34 dBm` | `42 ms` | `48.4 Mbps` | `32.3 Mbps` |
| 2 | `10:26` | `10 m`   | `Wi-Fi 6 / 48` | `-60 dBm` | `42 ms` | `60.7 Mbps` | `46.0 Mbps` |
| 3 | `10:27` | `20 m`   | `Wi-Fi 6 / 48` | `-66 dBm` | `42 ms` | `69.7 Mbps` | `39.9 Mbps` |
| 4 | `10:28` | `25 m`   | `Wi-Fi 6 / 48` | `-68 dBm` | `40 ms` | `26.9 Mbps` | `42.6 Mbps` |
| 5 | `10:29` | `30 m`   | `Wi-Fi 6 / 48` | `-68 dBm` | `38 ms` | `42.8 Mbps` | `38.5 Mbps` |

<details>
<summary>screenshots</summary>

![Screenshot_20240602-115533](https://github.com/codex-storage/nim-codex/assets/20563034/c60e490e-02c7-422b-99ea-8ab2198ca1e2)
![Screenshot_20240602-115537](https://github.com/codex-storage/nim-codex/assets/20563034/cf616b99-7ee8-4972-9d12-ecc78886fe5c)
![Screenshot_20240602-115543](https://github.com/codex-storage/nim-codex/assets/20563034/7990f5c1-9042-4edb-b752-b46d91d89e40)
![Screenshot_20240602-115548](https://github.com/codex-storage/nim-codex/assets/20563034/05015069-ec13-4da6-8af0-359a677c21d1)
![Screenshot_20240602-115556](https://github.com/codex-storage/nim-codex/assets/20563034/09f53be4-872b-4d47-a870-75378746fe61)

</details>


#### Conclusions
 1. Even on a 30 m distance signal is strength and phone was connected using Wi-Fi 6
 2. Internet latency and speed is more or less similar and does not depend on the distance
 3. With that setup we should be able to cover 20m x 20m open space

**Comment by veaceslavdoina** [comment]
### Internet 5G in Belgium
- [List of mobile network operators of Europe - Belgium](https://en.wikipedia.org/wiki/List_of_mobile_network_operators_of_Europe#Belgium)
- [5G NR frequency bands](https://en.wikipedia.org/wiki/5G_NR_frequency_bands)
- [spectrum-tracker.com/Belgium](https://www.spectrum-tracker.com/Belgium)
- [NETGEAR Nighthawk M6 Pro (MR6450)](https://www.netgear.com/uk/home/mobile-wifi/hotspots/mr6450/) (`n1, n2, n3, n5, n7, n8, n20, n28, n38, n40, n41, n71, n77, n78`)

#### Carriers
| # | Carier   | 5G Bands (?)      | 5G Coverage                                                                                                                                               | Plans                                                             | FAQ                                                                                                                                                                 |
| - | -------- | ----------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1 | Proximus | `n1, n3, n8, n28` | [map](https://www.proximus.be/support/en/id_sfaqr_map_network/personal/support/internet/internet-on-the-go/surf-on-5g-4g-or-3g/network-coverage-map.html) | [17-35 € /month](https://www.proximus.be/fiber-extreme/en/mobile) | [FAQ 5G](https://www.proximus.be/en/id_cr_5g_faq/personal/think-possible/think-possible-network/proximus-first-5g-network/frequently-asked-questions-about-5g.html) |
| 2 | Orange   | `n1, n3, n8, n28` | [map](https://www.orange.be/nl/opties-en-diensten/orange-netwerk/dekkingskaart)                                                                           | ?                                                                 | [FAQ 5G](https://www.orange.be/nl/opties-en-diensten/orange-netwerk/5g)                                                                                             |
| 3 | Base     | `n1, n3, n8, n28` | [map](https://www.prd.base.be/en/support/tools-networkmap/)                                                                                               | [12-32 € /month](https://www.prd.base.be/en/)                     | [All about 5G](https://www.prd.base.be/en/support/wi-fi-4g-5g/5g-connections/)                                                                                      |

[How to get a mobile phone number and SIM card in Belgium / Prepaid vs mobile contracts](https://www.expatica.com/be/living/household/belgium-sim-cards-and-mobile-phones-1028647/#compare-operators)
> As with many countries, expats have the choice of prepaid SIM cards or mobile contracts in Belgium. However, be aware that you won’t be able to take out a mobile contract unless you have registered at your local town hall. For many expats planning a longer stay, registration will take place soon after you arrive. **However, if you’re only staying for the short term you will be limited to prepaid SIMs.**


#### Quick conclussions
- Our 5G modem is compatible with Belgium operators
- Proximus probably can be most convenient, but that should be checked
- We might have port forwarding issue with mobile connection
- It is not clear if we can get right mobile plan in Belgium - should it be a contract and what documents do we need for that?

**Comment by emizzle** [comment]
eSIM option: https://www.airalo.com/belgium-esim
physical SIM option (tether with android?): https://simcorner.com/collections/belgium-sim-card/products/belgium-travel-sim-card-20gb

**Comment by veaceslavdoina** [comment]
Did a check with a generic (from ZTE MU5120) Type-C to Ethernet adapter  and Pixel 8 Pro with eSIM card
```shell
Laptop --> UniFi AP <--> Type-C-to-Ethernet <--> Phone
```
Internet works fine but we have a double NAT, because UniFi AP NAT is behind Android NAT.
And some discussions around that - [How to assign Mobile Data's public IP to host connected on hotspot?](https://android.stackexchange.com/questions/195374/how-to-assign-mobile-datas-public-ip-to-host-connected-on-hotspot)

An option would be to use a VPN with port forwarding to UniFi and port forwarding on UniFi to the clients
```
        p.fw       p.fw
Clients <--> UniFi <--> Cloud VPN --> Cloud Public IP
```

NETGEAR Nighthawk M6 Pro does not support eSIM and we can use for that type of connection only mobile Android phone.

And a list of the eSIM providers/services in case we decide to follow that way
<details>
<summary>providers/services</summary>

1. https://esim.holafly.com
2. https://bytesim.com
3. https://mobimatter.com
4. https://travel.vodafone.com
5. https://travel.orange.com
6. https://www.simoptions.com/esim-europe
7. https://www.esim.net
8. https://rapidesim.com
9. https://etravelsim.com
10. https://microesim.com
11. https://www.airhubapp.com
12. https://esimdb.com
</details>

We should be aware that not all of them provide an option to share the internet and especially on the unlimited plans.

**Comment by emizzle** [comment]
Maybe we should look at buying a router that supports this? Routers running ASUS Merlin can do this ([OVPN instructions but likely similar for wireguard](https://support.ovpn.com/hc/en-us/articles/18745211449492-Port-forwarding-in-AsusWRT-Merlin))

I’m personally running out of other ideas on how we can work around not having hole punching. It seems like even if we get hole punching, that it will only work in limited scenarios, hardly ideal for a workshop. So this workaround is important.

**Comment by veaceslavdoina** [comment]
We found a workaround for devices which does not support eSIM and that need to be tested
- [eSIM.me](https://esim.me)
- [5ber eSIM](https://esim.5ber.com/)

**Comment by veaceslavdoina** [comment]
### Belgium Internet testing plan

We discussed an option to go to the Brussels and perform 5G Internet connection and equipment we would like to use for a workshop.

<details>
<summary>More details</summary>

#### Plan
 - [ ] Take with you ~ 10 minutes
 - [ ] Check Mobile Internet packages/options ~ 1 hour
 - [ ] Prepare hardware for 5G tests ~ 10 minutes
 - [ ] Check Mobile Internet speed ~ 10 minutes
 - [ ] Check Mobile Internet port forwarding ~ 10 minutes
 - [ ] Check Mobile Internet simultaneous connection ~ 10 minutes
 - [ ] Check Wi-Fi in a workshop location ~ 1 hour

  Duration ~ 2:50 hours


#### Take with you
 - Laptop - fully charged
 - Android phone - fully charged
 - eSIM adapter with an eject tool
 - NetGear modem - fully changed battery
 - UniFi - with a power bank and type-c cable
 - Ethernet patch cable to connect NetGear and UniFi
 - Mikrotik Chateau 5G ax with power adapter


#### Check Mobile Internet packages/options ~ 1 hour

 In Belgium there are [3 mobile carrier](https://github.com/codex-storage/nim-codex/issues/781#issuecomment-2143828383):
   - Go to Proximus/Orange/Base and ask how we can purchase a package for 5G and 50/100/150GB of Internet traffic
   - Ask if we get a public IP - do not expect for technical answer
   - Ask if port forwarding will work - do not expect for technical answer


#### Prepare hardware for 5G tests ~ 10 minutes

 - Insert eSIM into the Android phone
 - Install eSIM into the eSIM adapter using [Android App](https://play.google.com/store/apps/details?id=esim.me)
 - Put eSIM adapter into NetGear
 - Power on NetGear ~ 2 minutes
 - Power on UniFi using power bank and type-c cable ~ 3 minutes
 - Connect UniFi to NetGear using ethernet cable


#### Check Mobile Internet speed ~ 10 minutes

 1. Connect to the UniFi Wi-Fi from a Android
 2. Open [WiFiman](https://play.google.com/store/apps/details?id=com.ubnt.usurvey) and authenticate using _UI Account_ account
 3. Run 3-5 tests in a row - results will be saved and available for further screenshots

 ----

 1. Connect to the UniFi Wi-Fi from a laptop
 2. Open https://www.speedtest.net in a browser
 3. Run 3-5 tests in a row and save results via screenshots or Share --> Web --> Copy/Paste


#### Check Mobile Internet port forwarding ~ 10 minutes

 1. Connect to the UniFi Wi-Fi from a laptop
 2. Check your Public IP - [ip.codex.storage](https://ip.codex.storage)
 3. Check your Private IP - `ipconfig`
 4. Open TCP port on laptop using Docker, based on your IP latest octet - `x.x.x.20'100`
    ```shell
    docker run \
      --rm \
      -p 20100:80 \
      nginx
    ```
    Connect to Public IP from Cloud VM
    ```shell
    curl public-ip:20100
    ```
 5. Open UDP port on laptop using Docker, based on your IP latest octet - `x.x.x.20'100`
    ```shell
    docker run --rm \
    -p 0.0.0.0:20100:5005/udp \
    --name udp-listener \
    -e UDPPORT=5005 \
    mendhak/udp-listener
    ```

    Connect to Public IP from Cloud VM
    ```shell
    # Connect
    nc -u localhost 20100

    # Send data
    Test --> Enter

    # Check result on the server side
    Test
    ```


#### Check Mobile Internet simultaneous connection ~ 10

 1. Run test using [iperf3](https://iperf.fr/iperf-doc.php) with 30, 50, 100 and save results
    ```shell
    docker run \
      --rm \
      networkstatic/iperf3 \
      --client 168.119.50.205 \
      --port 5201 \
      --parallel 30
     ```


#### Check Wi-Fi in a workshop location ~ 1 hour

 1. Find a workshop location
 2. Place eSIM card into Mikrotik router
 3. Place Mikrotik to the table and plug into power outlet
 4. Check Wi-Fi signal at the longest distance in the room using [WiFi Analyzer (open-source)](https://play.google.com/store/apps/details?id=com.vrem.wifianalyzer) - note signal level
 5. Check Internet speed at the longest distance in the room via https://speedtest.net - save the results
 6. Check Wi-Fi signal and speed in other parts of the room - save the results

**Comment by veaceslavdoina** [comment]
We have successfully tested with Ben
1. [eSIM to SIM adapter](https://esim.me) with a [Best Europe 30 GB](https://mobimatter.com/travel-esim/esimgo-best-europe-30-gb-esim?destination=europe) package and enabled roaming
2. Netgear with eSIM adapter and UniFi
    ![Netgear-UniFi-Speedtest](https://github.com/codex-storage/nim-codex/assets/20563034/712d498b-7fe6-4816-aac5-581b12cdc7e0)

3. Mikrotik with eSIM adapter
    ![Mikrotik-Speedtest](https://github.com/codex-storage/nim-codex/assets/20563034/d8d490aa-ddee-4835-b5f3-62ae7ab7faed)

**Comment by veaceslavdoina** [comment]
We ended up with the following solution
- [Mikrotik Chateau 5G ax](https://mikrotik.com/product/chateau_5g_ax) and local Wi-Fi network
- For Internet we use [eSIM.me](https://esim.me/) and [Best Europe 30 GB](https://mobimatter.com/travel-esim/esimgo-best-europe-30-gb-esim?destination=europe) package
- Codex Bootstrap node in local Wi-Fi network running on NUC
- Codex Storage nodes in local Wi-FI network running on NUC and laptops
- External Geth network to be able to use Faucets/Discordbot/Explorer
