### ISSUE TITLE
Workshop cheatsheet

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#786]
Instructions to be presented to and used by the workshop participants.
- workshop instructions reference (commands to run)
- cli reference (appendix)

**Comment by emizzle** [comment]
Same information as the interactive slides, but in a different format. Used for reference, as steps in same order.

1. Installation instructions: get binary from release page
2. How to run it: 
  - own machine / network? TBD
3. How to interact with it

Should not give too many options / too much text.

**Comment by gmega** [comment]
Hey @emizzle I'm closing this as I'm guessing it's just a leftover.
