### ISSUE TITLE
Ensure on validator start up that all active slots (for all SPs) are loaded 

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#795]
Currently, the validator only listens for request events, like storage requested, and adds slots to its list of slots to check for proofs submitted.

When the validator is started, populate the `slots` hashset with existing filled slots from the contract.

**Comment by AuHau** [comment]
Duplicate of https://github.com/codex-storage/nim-codex/issues/458 ;-)

**Comment by emizzle** [comment]
Closed as duplicate of #458
