### ISSUE TITLE
Add LICENSE file to repo's root

### ISSUE THREAD

**Issue by gmega** [codex-storage/nim-codex#830]
Apache v2, can probably copy [what's been done in nimbus](https://github.com/status-im/nimbus-eth1/blob/master/LICENSE-APACHEv2) with minor changes. Check if we're dual-licensing (MIT/Apache) as well.

**Comment by veaceslavdoina** [comment]
Looks like we can add more than one license file - [Easily discover and navigate to multiple licenses in repositories](https://github.blog/changelog/2022-05-26-easily-discover-and-navigate-to-multiple-licenses-in-repositories/)

And a simple experiment results - license in _LICENSE.md_ can't be detected and shown as `unknown`

<img width="1228" alt="Screenshot 2024-06-14 at 14 56 08" src="https://github.com/codex-storage/nim-codex/assets/20563034/5fa60e15-76ba-4241-8f3e-34df564833f0">

<img width="435" alt="Screenshot 2024-06-14 at 14 58 56" src="https://github.com/codex-storage/nim-codex/assets/20563034/edf2447e-658f-40b3-98a6-1f6a4470df24">
