### ISSUE TITLE
Upload huge files via chunks 

### ISSUE THREAD

**Issue by 2-towns** [codex-storage/nim-codex#866]
**Is your feature request related to a problem? Please describe.**
When attempting to upload a large file (6GB) using the SDK (and consequently the REST API) within the browser, the browser becomes unresponsive. To address this issue, I attempted to optimize the process by using a Web Worker, believing that it was caused by an overload on the UI thread; however, the problem persists.

**Describe the solution you'd like**
For the client, a viable solution would be to upload the file by segmenting it into smaller chunks (for instance, 10 MB per chunk), and sending individual requests for each chunk. 
The server would need to handle these separate chunks and merge them into the final file. 

Additionally, dividing the file into chunks for upload would enable resumable downloads.

**Describe alternatives you've considered**
Limit the file maximum size to 1.5 GB.   

**Additional context**
Here are some relevant links discussing the process of splitting large files into multiple chunks: 
- https://dev.to/codeparrot/how-google-drive-handles-huge-file-uploads-4c58
- https://docs.librephotos.com/docs/user-guide/mobile/librephotos-mobile/upload

**Comment by dryajov** [comment]
Are you trying to load the entire file into the browser and then initiating the upload or are you using the streaming API?

**Comment by 2-towns** [comment]
I tried to load the file into browser, pass it to the web worker (no issue, no freezing) and then initiate the upload with `XMLHttpRequest`: 

```js
  const url = this.url + Api.config.prefix + "/data";

    const xhr = new XMLHttpRequest();

    const promise = new Promise<SafeValue<string>>(async (resolve) => {
      xhr.upload.onprogress = (evt) => {
        if (evt.lengthComputable) {
          onProgress?.(evt.loaded, evt.total);
        }
      };

      xhr.open("POST", url, true);

      xhr.send(new Blob(await Chunks.split(file)));

      xhr.onload = function () {
        if (xhr.status != 200) {
          resolve({
            error: true,
            data: {
              code: xhr.status,
              message: xhr.responseText,
            },
          });
        } else {
          resolve({ error: false, data: xhr.response });
        }
      };

      xhr.onerror = function () {
        resolve({
          error: true,
          data: {
            message: "Something went wrong during the file upload.",
          },
        });
      };
    });
```

The Chunks.split(file) is splitting the file into multiple chunks to avoid the browser complaining about the file size. 
The reason I was using XMLHttpRequest is to have the upload indicator and notify the UI about the progress. 
This way is causing a big freeze into the browser. 

After your message, I was looking into a way to send the body as a stream and I found this API with fetch: 

```js
fetch(url, {
  method: 'POST',
  headers: {'Content-Type': 'text/plain'},
  body: stream,
  duplex: 'half',
});
```
Maybe it will make things better; I never tried this API. 
The downsides are it is only compatible with Chrome 105+ (no Firefox, no Safari) and it requires HTTP/2.

[Fetch streaming request](https://developer.chrome.com/docs/capabilities/web-apis/fetch-streaming-requests)

**Comment by AuHau** [comment]
I have implemented this feature as part of two storage related SDKs. I am happy to guide you as I can tell you this is big pain to implement. DMem me if you are interested ;-)

**Comment by 2-towns** [comment]
Thanks a lot @AuHau for the call and the debugging session.

Firstly, before using XMLHttpRequest to support the upload progress, I was using fetch, and I was receiving this error from the browser when trying to upload huge payload:

```
DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired
```

That's why I started to split the buffer into multiple chunks to move away from this error. But @AuHau pointed me out that this should be handled by the browser directly. So instead of splitting the buffer like this:

```js
xhr.send(new Blob(await Chunks.split(file)));
```

Just send the file as it is: 

```
xhr.send(file);
```

But when doing this, the browser is adding a content-type header which wasn't handled by the Codex client.

Finally to fix this issue we created an `OPTIONS` endpoint which allows the content-type header during the preflight request, and now the UI is responsive even with 6 Gb files. To summarize the process:

UI -> Upload file -> Pass to the worker -> Call the SDK from the worker -> Call the REST Api and notify the UI about the request progress -> the XMLHttpRequest passes the file to the HTTP protocol which manages the huge file itself

One concern is to make it compatible with NodeJS to have a SDK platform agnostic. To achieve this, we will need to try either checking how fetch in Node handles the upload with huge files or test with a third-party library like axios.

I'll submit a PR with the CORS endpoint added for the preflight request.

**Comment by dryajov** [comment]
> UI -> Upload file -> Pass to the worker -> Call the SDK from the worker -> Call the REST Api and notify the UI about the request progress -> the XMLHttpRequest passes the file to the HTTP protocol which manages the huge file itself

Do you really need the worker if you using a streaming api?

**Comment by 2-towns** [comment]
> Do you really need the worker if you using a streaming api? 

It seems that using XMLHttpRequest with asynchronous flag + streaming api should not block the main UI thread. 

I will do some testing today to be sure.
