### ISSUE TITLE
[BUG] Missing 'erasure' and 'por' Fields in getPurchase endpoint despite documentation

### ISSUE THREAD

**Issue by 2-towns** [codex-storage/nim-codex#894]
**Describe the bug**
In the OpenAPI documentation, the getPurchase endpoint specifies that the attributes erasure and por should be included in the content element. However, when using the API, those fields are not present.

**To Reproduce**
Retrieve the purchase details of a request

**Expected behavior**
The documentation should be updated, or the fields should be added to the data returned by the endpoint.

**Screenshots**
```json
{
    "requestId": "0x2ed98983e2f9b30827e6b15f87ac177937c2fc29354ee5de35e050f748e6715a",
    "request": {
        "client": "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc",
        "ask": {
            "slots": 3,
            "slotSize": "131072",
            "duration": "86400",
            "proofProbability": "1",
            "reward": "10",
            "collateral": "10",
            "maxSlotLoss": 1
        },
        "content": {
            "cid": "zDvZRwzkwLcFPSWKbJD3Dd1fwhjdY2Gk4ybsVNxtJSCZe9FJh1Cf"
        },
        "expiry": "18000",
        "nonce": "0xa9dfbb3ce1a7b73ebec3d9912b697360f737316ae07b5d22401c3817aed7c3c0",
        "id": "0x2ed98983e2f9b30827e6b15f87ac177937c2fc29354ee5de35e050f748e6715a"
    },
    "state": "submitted",
    "error": null
}
``` 

**Environment:**
- OS: Linux
- Version: 22
- Tag/Commit: Master
- Arch: amd64

**Additional context**

**Comment by emizzle** [comment]
https://github.com/codex-storage/nim-codex/pull/915 should fix this 👍
