### ISSUE TITLE
[BUG] Codex won't run with glibc 2.31

### ISSUE THREAD

**Issue by gmega** [codex-storage/nim-codex#932]
Our binaries don't seem to support the [current version](https://launchpad.net/ubuntu/+source/glibc) for glibc (2.31) in Focal Fossa for some reason. I don't know why, out of all versions, this one seems to have been skipped.

```bash
➜  scripts git:(master) ✗ ldd -v codex-v0.1.4-linux-amd64 | grep 'libc.so.6 (GLIBC' | sed 's/.*GLIBC_\(.*\)).*$/\1/g' | sort | uniq | grep '2.3[0-9]*'
2.3
2.3.2
2.32
2.33
2.3.4
2.34
2.35
```

**Comment by Shelpin** [comment]
Thanks a lot for opening the issue! hope to be able to run my codex node soon :))))....big congrats on the launch! and a big THANKS!

**Comment by veaceslavdoina** [comment]
Just created a [new branch](https://github.com/codex-storage/nim-codex/tree/refs/heads/fix/use-ubuntu-20-04-for-linux-builds) and [run a release workflow](https://github.com/codex-storage/nim-codex/actions/runs/11152216422).

Let's wait for an artifacts and check linux binary.
