### ISSUE TITLE
[BUG] node/peeris API call returns 404

### ISSUE THREAD

**Issue by vpavlin** [codex-storage/nim-codex#949]
**Describe the bug**
Based on https://api.codex.storage/#tag/Node/operation/getPeerId

I should be able to get peerId by calling

```
curl -v http://localhost:8080/api/codex/v1/node/peerid
```

Same for `/node/spr`

But I get `404 Not Found`
**To Reproduce**
1. Run 0.1.6
2. `curl -v http://localhost:8080/api/codex/v1/node/peerid`

**Expected behavior**
Return peerId

**Environment:**
 - OS: ubuntu
 - Version: 0.1.6

 - Arch amd64:

**Additional context**

**Comment by AuHau** [comment]
Seems like it is now: `/api/codex/v1/peerid`.

https://github.com/codex-storage/nim-codex/blob/4b9336ec073d1b7e45131b15254025570fbd49c1/codex/rest/api.nim#L588

Hmmm somebody ignored OpenAPI when renaming endpoints - great 🙄 Will fix it.
